### ISSUE TITLE
Use of `nonlocal` scope keyword breaks Python2.7 compatibility.

### ISSUE THREAD

**Issue by NightKhaos** [taylorb-syd/accustom#7]
Python3 introduced the `nonlocal` scope to allow for accessing variables outside of the default scope. This has proved very helpful in writing closures which the decorator can be thought as one big closure.

Unfortunately as the `nonlocal` keyword is not understood by Python2.7 this will result in import errors, requiring us to refactor the code to account for the limitations of Python2.7 scoping.

For now, this library will be only supported using Python3.6. If Python2.7 is required please write your use case here and I will put effort into updating the library to fix the scoping issues.

**Comment by taylorb-syd** [comment]
Python 2.7 will be deprecated soon. Closing this issue out.
